# Generated by Django 2.1.7 on 2019-03-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='app_name',
            new_name='title',
        ),
    ]
